version: "3"

services:
  presta_ckt:
    image: davpiatek/presta_docker:latest
    container_name: ps_ckt
    depends_on:
      - mariadb_ckt
    env_file:
      - .env
    networks:
      - nw-ckt

  mariadb_ckt:
    image: mariadb
    container_name: db_ckt
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./docker/app/config/parameters.php:/presthost/core/app/config/parameters.php 
    networks:
      - nw-ckt

networks:
  nw-ckt:
    driver: bridge