services:
  _defaults:
    public: true

  ps_checkout.payment.serializer:
    class: Symfony\Component\Serializer\Serializer
    factory: ['@PsCheckout\Api\Http\Serializer\PaymentSerializerFactory', 'create']

  PsCheckout\Api\Http\CheckoutHttpClient:
    class: PsCheckout\Api\Http\CheckoutHttpClient
    arguments:
      - '@PsCheckout\Api\Http\Configuration\CheckoutClientConfigurationBuilder'

  PsCheckout\Api\Http\OrderHttpClient:
    class: PsCheckout\Api\Http\OrderHttpClient
    arguments:
      - '@PsCheckout\Api\Http\Configuration\OrderHttpClientConfigurationBuilder'

  PsCheckout\Api\Http\OrderShipmentTrackingHttpClient:
    class: PsCheckout\Api\Http\OrderShipmentTrackingHttpClient
    arguments:
      - '@PsCheckout\Api\Http\Configuration\OrderShipmentTrackingConfigurationBuilder'

  PsCheckout\Api\Http\PaymentHttpClient:
    class: PsCheckout\Api\Http\PaymentHttpClient
    arguments:
      - '@PsCheckout\Api\Http\Configuration\PaymentHttpClientConfigurationBuilder'
      - '@ps_checkout.payment.serializer'

  PsCheckout\Api\Http\WebhookHttpClient:
    class: PsCheckout\Api\Http\WebhookHttpClient
    arguments:
      - '@PsCheckout\Api\Http\Configuration\WebhookHttpClientConfigurationBuilder'

  PsCheckout\Api\Http\MaaslandOrderHttpClient:
    class: PsCheckout\Api\Http\MaaslandOrderHttpClient
    arguments:
      - '@PsCheckout\Api\Http\Configuration\MaaslandOrderHttpClientConfigurationBuilder'