export const ALERT_TYPE_INFO = 'ALERT_TYPE_INFO';
export const ALERT_TYPE_WARNING = 'ALERT_TYPE_WARNING';
export const ALERT_TYPE_DANGER = 'ALERT_TYPE_DANGER';
export const ALERT_TYPE_SUCCESS = 'ALERT_TYPE_SUCCESS';
