export const EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND';
export const INVALID_EMAIL = 'INVALID_EMAIL';
export const INVALID_PASSWORD = 'INVALID_PASSWORD';
export const EMAIL_EXISTS = 'EMAIL_EXISTS';
export const MISSING_PASSWORD = 'MISSING_PASSWORD';
export const MISSING_EMAIL = 'MISSING_EMAIL';
