services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  PrestaShop\Module\PrestashopCheckout\Http\MaaslandHttpClient:
    class: PrestaShop\Module\PrestashopCheckout\Http\MaaslandHttpClient
    arguments:
      - "@ps_checkout.http.client"

  PrestaShop\Module\PrestashopCheckout\Http\CheckoutHttpClient:
    class: PrestaShop\Module\PrestashopCheckout\Http\CheckoutHttpClient

  PrestaShop\Module\PrestashopCheckout\Builder\Configuration\MaaslandHttpClientConfigurationBuilder:
    class: PrestaShop\Module\PrestashopCheckout\Builder\Configuration\MaaslandHttpClientConfigurationBuilder

  PrestaShop\Module\PrestashopCheckout\Http\HttpClientFactory:
    class: PrestaShop\Module\PrestashopCheckout\Http\HttpClientFactory

  ps_checkout.http.client:
    class: PrestaShop\Module\PrestashopCheckout\Http\HttpClientInterface
    factory: ['@PrestaShop\Module\PrestashopCheckout\Http\HttpClientFactory', "create"]
    arguments:
      - '@PrestaShop\Module\PrestashopCheckout\Builder\Configuration\MaaslandHttpClientConfigurationBuilder'

  PrestaShop\Module\PrestashopCheckout\Builder\Configuration\CheckoutClientConfigurationBuilder:
    class: PrestaShop\Module\PrestashopCheckout\Builder\Configuration\CheckoutClientConfigurationBuilder
