services:
  PrestaShop\Module\PrestashopCheckout\Http\MaaslandHttpClient:
    class: 'PrestaShop\Module\PrestashopCheckout\Http\MaaslandHttpClient'
    public: true
    arguments:
      - "@ps_checkout.http.client"

  PrestaShop\Module\PrestashopCheckout\Http\CheckoutHttpClient:
    class: 'PrestaShop\Module\PrestashopCheckout\Http\CheckoutHttpClient'
    public: true
    arguments:
      - '@PrestaShop\Module\PrestashopCheckout\Builder\Configuration\CheckoutClientConfigurationBuilder'

  PrestaShop\Module\PrestashopCheckout\Builder\Configuration\MaaslandHttpClientConfigurationBuilder:
    class: 'PrestaShop\Module\PrestashopCheckout\Builder\Configuration\MaaslandHttpClientConfigurationBuilder'
    public: true
    arguments:
      - '@PrestaShop\Module\PrestashopCheckout\Environment\Env'
      - '@PrestaShop\Module\PrestashopCheckout\Routing\Router'
      - '@PrestaShop\Module\PrestashopCheckout\ShopContext'
      - '@PrestaShop\Module\PrestashopCheckout\Repository\PsAccountRepository'
      - '@PrestaShop\Module\PrestashopCheckout\Context\PrestaShopContext'
      - '@PrestaShop\Module\PrestashopCheckout\Logger\LoggerConfiguration'
      - "@ps_checkout.logger"

  PrestaShop\Module\PrestashopCheckout\Http\HttpClientFactory:
    class: 'PrestaShop\Module\PrestashopCheckout\Http\HttpClientFactory'
    public: true

  ps_checkout.http.client:
    class: 'PrestaShop\Module\PrestashopCheckout\Http\HttpClientInterface'
    public: true
    factory: ['@PrestaShop\Module\PrestashopCheckout\Http\HttpClientFactory', "create"]
    arguments:
      - '@PrestaShop\Module\PrestashopCheckout\Builder\Configuration\MaaslandHttpClientConfigurationBuilder'

  PrestaShop\Module\PrestashopCheckout\Builder\Configuration\CheckoutClientConfigurationBuilder:
    class: 'PrestaShop\Module\PrestashopCheckout\Builder\Configuration\CheckoutClientConfigurationBuilder'
    public: true
    arguments:
      - '@PrestaShop\Module\PrestashopCheckout\Environment\Env'
      - '@PrestaShop\Module\PrestashopCheckout\Routing\Router'
      - '@PrestaShop\Module\PrestashopCheckout\ShopContext'
      - '@PrestaShop\Module\PrestashopCheckout\Repository\PsAccountRepository'
      - '@PrestaShop\Module\PrestashopCheckout\Context\PrestaShopContext'
      - '@PrestaShop\Module\PrestashopCheckout\Logger\LoggerConfiguration'
      - "@ps_checkout.logger"
