services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  PrestaShop\Module\PrestashopCheckout\Logger\LoggerDirectory:
    class: PrestaShop\Module\PrestashopCheckout\Logger\LoggerDirectory
    arguments:
      - !php/const _PS_VERSION_
      - !php/const _PS_ROOT_DIR_

  PrestaShop\Module\PrestashopCheckout\Logger\LoggerFilename:
    class: PrestaShop\Module\PrestashopCheckout\Logger\LoggerFilename
    arguments:
      - '@=service("ps_checkout.module").name'
      - '@=service("PrestaShop\\Module\\PrestashopCheckout\\Shop\\ShopProvider").getIdentifier()'

  PrestaShop\Module\PrestashopCheckout\Logger\LoggerConfiguration:
    class: PrestaShop\Module\PrestashopCheckout\Logger\LoggerConfiguration

  PrestaShop\Module\PrestashopCheckout\Logger\LoggerHandlerFactory:
    class: PrestaShop\Module\PrestashopCheckout\Logger\LoggerHandlerFactory
    arguments:
      - '@=service("PrestaShop\\Module\\PrestashopCheckout\\Logger\\LoggerDirectory").getPath()'
      - '@=service("PrestaShop\\Module\\PrestashopCheckout\\Logger\\LoggerFilename").get()'
      - '@=service("PrestaShop\\Module\\PrestashopCheckout\\Logger\\LoggerConfiguration").getMaxFiles()'
      - '@=service("PrestaShop\\Module\\PrestashopCheckout\\Logger\\LoggerConfiguration").getLevel()'

  ps_checkout.logger.handler:
    class: Monolog\Handler\HandlerInterface
    factory: ['@PrestaShop\Module\PrestashopCheckout\Logger\LoggerHandlerFactory', "build"]

  PrestaShop\Module\PrestashopCheckout\Logger\LoggerFactory:
    class: PrestaShop\Module\PrestashopCheckout\Logger\LoggerFactory
    arguments:
      - '@=service("ps_checkout.module").name'
      - "@ps_checkout.logger.handler"

  ps_checkout.logger:
    class: Psr\Log\LoggerInterface
    factory: ['@PrestaShop\Module\PrestashopCheckout\Logger\LoggerFactory', "build"]
    arguments:
      - '@PrestaShop\Module\PrestashopCheckout\Logger\LoggerDirectory'

  Psr\Log\LoggerInterface $psCheckoutLogger:
    alias: 'ps_checkout.logger'
