name: PHPStan

on:
  pull_request:
  push:
    branches:
      - main
      - '5.*'

jobs:
  prestashop:
    name: ${{ matrix.ps-version }}
    strategy:
      matrix:
        ps-version: ['ps17', 'ps8', 'ps9']
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
      - run: composer install
      - run: |
          composer install --ignore-platform-reqs
          composer phpstan:ci
        working-directory: ${{ matrix.ps-version }}
