name: PrestaShop 8 - Clean zips from buckets after merged PR

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - "prestashop/8.x"

env:
  ZIP_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}

jobs:
  remove_zips:
    name: Remove zips related to closed PR
    runs-on: ubuntu-latest

    steps:
      - name: Remove outdated integration zips
        shell: bash
        run: gcloud storage rm gs://ps-eu-w1-checkout-assets-integration/zips/ps8/${{ github.event.repository.name }}-integration-pr${{ github.event.number }}*

      - name: Remove outdated preproduction zips
        shell: bash
        run: gcloud storage rm gs://ps-eu-w1-checkout-assets-preproduction/zips/ps8/${{ github.event.repository.name }}-preproduction-pr${{ github.event.number }}*
